import { describe, it, expect } from 'vitest'
import { AgentGateRejectedError, deriveLegacyVaultId } from '@baishou/shared'
import { AgentTool, ToolContext } from '../tools/agent.tool'
import { z } from 'zod'

class MockWeatherTool extends AgentTool<z.ZodObject<{ location: z.ZodString }>> {
  readonly name = 'get_weather'
  readonly description = 'Get current weather for a location'
  readonly parameters = z.object({
    location: z.string()
  })

  async execute(args: { location: string }, context: ToolContext): Promise<string> {
    return `Weather in ${args.location} (Vault: ${context.vaultName}) is Sunny.`
  }
}

describe('AgentTool', () => {
  it('should define basic properties correctly', () => {
    const weatherTool = new MockWeatherTool()
    expect(weatherTool.name).toBe('get_weather')
    expect(weatherTool.description).toBe('Get current weather for a location')
  })

  it('should convert to Vercel AI CoreTool correctly', async () => {
    const weatherTool = new MockWeatherTool()
    const mockContext: ToolContext = {
      sessionId: 's1',
      vaultId: deriveLegacyVaultId('main-vault'),
      vaultName: 'main-vault'
    }

    const vercelTool = weatherTool.toVercelTool(mockContext) as any

    expect(vercelTool.description).toBe('Get current weather for a location')

    // Test the bound execution function generated by toVercelTool
    const result = await vercelTool.execute({ location: 'Tokyo' })
    expect(result).toBe('Weather in Tokyo (Vault: main-vault) is Sunny.')
  })

  it('should rethrow a gate rejection instead of returning a tool failure string', async () => {
    class RejectingTool extends AgentTool<z.ZodObject<{ question: z.ZodString }>> {
      readonly name = 'companion_ask'
      readonly description = 'Ask'
      readonly parameters = z.object({ question: z.string() })

      async execute(): Promise<string> {
        throw new AgentGateRejectedError()
      }
    }

    const vercelTool = new RejectingTool().toVercelTool({
      sessionId: 's1',
      vaultId: deriveLegacyVaultId('main-vault'),
      vaultName: 'main-vault'
    })

    await expect(vercelTool.execute({ question: '继续吗？' })).rejects.toBeInstanceOf(
      AgentGateRejectedError
    )
  })
})
