import React from 'react'
import { StatusBar } from 'react-native'
import { ScreenSafeArea } from '../../components/ScreenSafeArea'
import { AgentChatList } from './components/AgentChatList'
import { AgentScreenOverlays } from './components/AgentScreenOverlays'
import { AgentGateCardHost } from '../../components/agent-gate/AgentGateCardHost'
import { useAgentScreenController } from './hooks/useAgentScreenController'

export const AgentScreen = () => {
  const c = useAgentScreenController()

  return (
    <>
      <StatusBar
        barStyle={c.isDark ? 'light-content' : 'dark-content'}
        backgroundColor={c.colors.bgApp}
      />
      <ScreenSafeArea preset="tab" style={{ backgroundColor: c.colors.bgApp }}>
        <AgentChatList
          colors={c.colors}
          isDark={c.isDark}
          t={c.t}
          resolvedChatBackgroundUri={c.resolvedChatBackgroundUri}
          chatBackgroundBlur={c.chatBackgroundBlur}
          chatBackgroundOverlay={c.chatBackgroundOverlay}
          userProfile={c.userProfile}
          displayModelName={c.displayModelName}
          currentProviderId={c.currentProviderId}
          currentProviderType={c.currentProviderType}
          totalCostMicros={c.totalCostMicros}
          setDrawerOpen={c.setDrawerOpen}
          setShowModelSwitcher={c.setShowModelSwitcher}
          setShowCostDialog={c.setShowCostDialog}
          drawerSwipeEnabled={c.drawerSwipeEnabled}
          flatListRef={c.flatListRef}
          listContentStyle={c.streaming.listContentStyle}
          handleListScroll={c.handleListScroll}
          handleScrollBeginDrag={c.handleScrollBeginDrag}
          handleScrollEndDrag={c.handleScrollEndDrag}
          handleMomentumScrollBegin={c.handleMomentumScrollBegin}
          handleMomentumScrollEnd={c.handleMomentumScrollEnd}
          handleListContentSizeChange={c.handleListContentSizeChange}
          handleListIntrinsicContentHeightChange={c.handleListIntrinsicContentHeightChange}
          listViewportHeight={c.listViewportHeight}
          setListViewportHeight={c.setListViewportHeight}
          layoutReadyRef={c.layoutReadyRef}
          messages={c.messages}
          hasMore={c.hasMore}
          showLoadMoreBanner={c.showLoadMoreBanner}
          handleLoadMore={c.handleLoadMore}
          isStreaming={c.isStreaming}
          isStreamBridgeActive={c.isStreamBridgeActive}
          renderEmptyState={c.streaming.renderEmptyState}
          chatRows={c.streaming.chatRows}
          hasStreamingBody={c.streaming.hasStreamingBody}
          renderStreamingDots={c.streaming.renderStreamingDots}
          streamingText={c.streamingText}
          streamingReasoning={c.streamingReasoning}
          chatUserProfile={c.chatUserProfile}
          chatAiProfile={c.chatAiProfile}
          hasChatBackground={c.hasChatBackground}
          liveStreamProps={c.streaming.liveStreamProps}
          compressionPhase={c.compressionPhase}
          compressionTriggerMessageId={c.compressionTriggerMessageId}
          isCompressing={c.isCompressing}
          compressionText={c.compressionText}
          compressionReasoning={c.compressionReasoning}
          IDLE_LIVE_COMPRESSION={c.streaming.IDLE_LIVE_COMPRESSION}
          lastMessage={c.lastMessage}
          liveAssistantActive={c.streaming.liveAssistantActive}
          keepLiveRowAfterHold={c.streaming.keepLiveRowAfterHold}
          markdownPresentationActive={c.streaming.markdownPresentationActive}
          bubbleTextStreaming={c.streaming.bubbleTextStreaming}
          streamingThinkLoading={c.streaming.streamingThinkLoading}
          activeToolDisplayName={c.activeToolDisplayName}
          streamingCompletedTools={c.streaming.streamingCompletedTools}
          editingMessageId={c.editingMessageId}
          editingRowRef={c.editingRowRef}
          handleRegenerate={c.handleRegenerate}
          handleResend={c.handleResend}
          handleEditMessage={c.handleEditMessage}
          handleSaveAssistantEdit={c.handleSaveAssistantEdit}
          handleDeleteMessage={c.handleDeleteMessage}
          handleTtsReadAloud={c.handleTtsReadAloud}
          ttsPlayingMsgId={c.ttsPlayingMsgId}
          handleShowContext={c.handleShowContext}
          handleBranch={c.handleBranch}
          handleBubbleEditingChange={c.handleBubbleEditingChange}
          isRetryActionBusy={c.isRetryActionBusy}
          listFooter={c.streaming.listFooter}
          showScrollButton={c.showScrollButton}
          isBubbleEditing={c.isBubbleEditing}
          scrollButtonAnimatedStyle={c.scrollButtonAnimatedStyle}
          scrollToBottom={c.scrollToBottom}
          inputDockHeight={c.inputDockHeight}
          setInputDockHeight={c.setInputDockHeight}
          inputDockAnimatedStyle={c.inputDockAnimatedStyle}
          inputBarRef={c.inputBarRef}
          handleSendWithScroll={c.handleSendWithScroll}
          isLoading={c.isLoading}
          handleStop={c.handleStop}
          hasConfiguredDialogueModel={c.hasConfiguredDialogueModel}
          toast={c.toast}
          composerDraftKey={c.composerDraftKey}
          handleInputBarFocus={c.handleInputBarFocus}
          shortcuts={c.shortcuts}
          assistantDisplayName={c.assistantDisplayName}
          setShowShortcutSheet={c.setShowShortcutSheet}
          setShowRecallSheet={c.setShowRecallSheet}
          router={c.router}
          searchMode={c.searchMode}
          toggleSearchMode={c.toggleSearchMode}
          ttsMode={c.ttsMode}
          toggleTtsMode={c.toggleTtsMode}
        />
      </ScreenSafeArea>
      <AgentGateCardHost request={c.pendingAgentGate} onReply={c.replyAgentGate} />
      <AgentScreenOverlays
        drawerOpen={c.drawerOpen}
        setDrawerOpen={c.setDrawerOpen}
        currentAssistant={c.currentAssistant}
        resolvedCurrentAvatarUri={c.resolvedCurrentAvatarUri}
        pinnedAssistants={c.pinnedAssistants}
        sessions={c.sessions}
        sessionListScrollKey={c.sessionListScrollKey}
        hasMoreSessions={c.hasMoreSessions}
        isLoadingMoreSessions={c.isLoadingMoreSessions}
        loadSessions={c.loadSessions}
        currentSessionId={c.currentSessionId}
        handleSelectSession={c.handleSelectSession}
        handleCreateSession={c.handleCreateSession}
        refreshSessionList={c.refreshSessionList}
        setShowAssistantPicker={c.setShowAssistantPicker}
        handleSelectAssistantWithTracking={c.handleSelectAssistantWithTracking}
        handlePinSession={c.handlePinSession}
        handleDeleteSession={c.handleDeleteSession}
        handleRenameSession={c.handleRenameSession}
        showAssistantPicker={c.showAssistantPicker}
        showModelSwitcher={c.showModelSwitcher}
        setShowModelSwitcher={c.setShowModelSwitcher}
        handleSelectModel={c.handleSelectModel}
        currentProviderId={c.currentProviderId}
        currentModelId={c.currentModelId}
        showCostDialog={c.showCostDialog}
        setShowCostDialog={c.setShowCostDialog}
        displayModelName={c.displayModelName}
        totalInputTokens={c.totalInputTokens}
        totalOutputTokens={c.totalOutputTokens}
        totalCacheReadInputTokens={c.totalCacheReadInputTokens}
        totalCacheWriteInputTokens={c.totalCacheWriteInputTokens}
        estimatedCost={c.estimatedCost}
        pricingLastUpdated={c.pricingLastUpdated}
        handleRefreshPricing={c.handleRefreshPricing}
        showShortcutSheet={c.showShortcutSheet}
        setShowShortcutSheet={c.setShowShortcutSheet}
        shortcuts={c.shortcuts}
        handleShortcutSelect={c.handleShortcutSelect}
        addShortcut={c.addShortcut}
        updateShortcut={c.updateShortcut}
        deleteShortcut={c.deleteShortcut}
        reorderShortcuts={c.reorderShortcuts}
        showRecallSheet={c.showRecallSheet}
        setShowRecallSheet={c.setShowRecallSheet}
        recallItems={c.recallItems}
        isSearchingRecall={c.isSearchingRecall}
        handleRecallSearch={c.handleRecallSearch}
        handleInjectRecall={c.handleInjectRecall}
        recallSearchMode={c.recallSearchMode}
        toggleRecallSearchMode={c.toggleRecallSearchMode}
        recallLookbackMonths={c.recallLookbackMonths}
        setRecallLookbackMonths={c.setRecallLookbackMonths}
        services={c.services}
        i18n={c.i18n}
        copyPrefix={c.copyPrefix}
        setCopyPrefix={c.setCopyPrefix}
        recallCopyPreview={c.recallCopyPreview}
        recallCopyPreviewLoading={c.recallCopyPreviewLoading}
        toast={c.toast}
        t={c.t}
        contextDialogState={c.contextDialogState}
        setContextDialogState={c.setContextDialogState}
        activeContextSessionId={c.activeContextSessionId}
        contextRecompressJob={c.contextRecompressJob}
        isCompressing={c.isCompressing}
        compressionPhase={c.compressionPhase}
        compressionText={c.compressionText}
        compressionReasoning={c.compressionReasoning}
        runContextRecompress={c.runContextRecompress}
        dismissContextRecompressError={c.dismissContextRecompressError}
        pickerAssistants={c.pickerAssistants}
        loadAssistants={c.loadAssistants}
      />
    </>
  )
}
