export * from './theme'
export * from './hooks'
export * from './utils/heatmap-matrix'
export * from './utils/formatSyncProgress'
export { getProviderIcon } from './utils/provider-icons'

export * from './desktop/Button/Button'
export * from './desktop/Card/Card'
export * from './desktop/Input/Input'
export * from './desktop/Toast/Toast'
export * from './desktop/Toast/useToast'
export * from './desktop/Dialog/index'
export * from './desktop/Modal/Modal'
export * from './desktop/RestoreBlockingOverlay/index'
export * from './desktop/Switch/Switch'
export * from './desktop/Select/Select'
export * from './desktop/Badge/Badge'
export * from './desktop/Tooltip/Tooltip'
export * from './desktop/HelpTooltip/index'

export * from './desktop/DiaryCard/index'
export * from './desktop/DiaryMetaCard/index'
export * from './desktop/MoodIcon/index'
export * from './desktop/WeatherIcon/index'
export * from './desktop/TimelineNode/index'
export * from './desktop/TagInput/index'
export * from './desktop/DatePicker/index'
export * from './desktop/PageSizeSelector/index'
export * from './desktop/Pagination/index'
export * from './desktop/DiaryEditor/index'
export * from './desktop/MarkdownRenderer/index'
export * from './desktop/ContextMenu/index'

export * from './desktop/SummaryCard/index'
export * from './desktop/MissingSummaryCard/MissingSummaryCard'
export * from './desktop/StatisticCard/index'

// Editor Addons

export * from './desktop/DiaryEditorAppBarTitle/DiaryEditorAppBarTitle'

// Dashboard
export * from './desktop/DashboardHeroBanner/DashboardHeroBanner'
export * from './desktop/DashboardStatsCard/DashboardStatsCard'
export * from './desktop/DashboardSharedMemoryCard/DashboardSharedMemoryCard'
export * from './desktop/ActivityHeatmap/index'
export * from './desktop/SummaryDashboard/index'
export * from './desktop/GalleryPanel/index'
export * from './desktop/SettingsSection/index'
export * from './desktop/SettingsItem/index'
export * from './desktop/ColorPicker/index'
export * from './desktop/AppearanceSettingsCard/AppearanceSettingsCard'
export * from './desktop/WorkspaceSettingsCard/index'
export * from './desktop/DataManagementCard/index'
export * from './desktop/LanSyncCard/index'
export * from './desktop/CloudSyncPanel/index'
export * from './desktop/GitManagementPage/index'
export * from './desktop/VersionHistorySidebar/index'
export * from './desktop/StorageSettingsCard/index'
export * from './desktop/AttachmentManagementView/index'

export * from './desktop/AIModelServicesView/index'
export * from './desktop/AIGlobalModelsView/index'
export * from './desktop/TTSProviderSettings/index'
export * from './desktop/AgentBehaviorSettingsCard/index'
export * from './desktop/IdentitySettingsCard/index'
export {
  updateRecentPersonaIds,
  renameRecentPersonaId,
  removeRecentPersonaId,
  pickRecentPersonaIds,
  pickQuickSwitchPersonaIds
} from './desktop/IdentitySettingsCard/identity-recent.utils'

export * from './desktop/RagMemoryView/index'
export * from './desktop/AgentToolsView/index'
export * from './desktop/AgentGateDock/index'
export * from './desktop/AgentGatePartBubble/index'
export * from './agent-gate/index'
export * from './agent-workspace/index'
export * from './desktop/WebSearchSettingsView/index'
export * from './desktop/SummarySettingsView/index'

export * from './desktop/ProfileSettingsCard/index'
export * from './desktop/AvatarCropModal/index'
export * from './desktop/ChatBackgroundSettingsCard/index'
export * from './desktop/HotkeySettingsCard/index'
export * from './desktop/McpSettingsCard/index'
export * from './desktop/DeveloperOptionsView/index'

export * from './desktop/AboutSettingsCard/index'
export * from './desktop/feedback/useOpenFeedbackChannel'
export * from './desktop/AssistantManagementView/index'
export * from './desktop/AssistantMatrixCard/index'
export * from './desktop/UpdateChecker/index'
export * from './desktop/VersionManager/index'

// 仅保证 TypeScript 导出正常，真正跨包可能会区分 desktop / native 导出策略

// 聊天与Agent组件
export * from './desktop/ChatBubble/index'
export * from './desktop/StreamingBubble/index'
export * from './desktop/CompressionDivider/index'
export * from './desktop/CompressionActivityBar/index'
export * from './desktop/ThinkingBlock/index'
export * from './desktop/AgentMarkdown/index'
export * from './desktop/TokenBadge/index'
export * from './desktop/ToolResultGroupCard/index'
export * from './desktop/AgentToolChain'
export * from './desktop/InputBar/index'
export * from './desktop/ModelSwitcher/index'
export * from './desktop/AssistantPicker/index'
export * from './desktop/SessionListItem/index'
export * from './desktop/EmojiPicker/index'
export * from './desktop/ChatAppBar/index'
export * from './desktop/AgentSessionList/index'

// Core Management UI (B2)
export * from './desktop/SessionManagementPage/index'
export * from './desktop/AssistantManagementPage/index'
export * from './desktop/AssistantEditPage/index'
export * from './desktop/AssistantAvatarPicker'
export * from './desktop/AssistantAvatar'
export * from './desktop/AssistantKindTabBar'
export * from './desktop/AssistantKindBadge'
export { resolveDesktopAssistantAvatarSrc } from './desktop/assistant-avatar.util'
export * from './desktop/ChatCostDialog/index'
export * from './desktop/ContextChainDialog/index'
export * from './desktop/ContextChainPanel/index'
export { AssistantPickerSheet } from './desktop/AssistantPickerSheet/index'
export type { AssistantPickerSheetProps } from './desktop/AssistantPickerSheet/index'
export * from './desktop/PromptShortcutSheet/index'
export * from './desktop/RecallDialog/index'
export { resolveActiveToolDisplayName } from './shared/tool-result.util'
export * from './desktop/ModelSwitcherPopup'
export * from './shared/ModelVisionBadge'
export * from './desktop/AvatarEditor'
export * from './desktop/IncrementalSyncPanel/index'
export * from './desktop/IncrementalSyncScopeList/index'
export * from './desktop/SyncModeComparisonNotice/index'
export * from './desktop/BackupScopeList/index'
