/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-reasoning-models.mjs — do not edit by hand.
 * Source: https://models.dev/api.json + scripts/provider-modelsdev.manifest.json
 */
export const REASONING_MODELS_SNAPSHOT = {
  "syncedAt": "2026-09-16T19:32:49.277Z",
  "source": "https://models.dev/api.json",
  "byProvider": {
    "openai": {
      "gpt-5-nano": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-pro": {
        "values": [
          "high"
        ]
      },
      "gpt-5.6-sol": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-6-astra": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.3-codex-spark": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.1": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "o1": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.6-luna": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.3-codex": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o1-pro": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.4-nano": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.5-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-mini": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5-mini": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.4-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-terra": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.2-chat-latest": {
        "values": [
          "medium"
        ]
      },
      "o4-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-realtime-2.1": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o3-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "o3": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "o3-pro": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.5": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      }
    },
    "gemini": {
      "gemini-3.1-pro-preview-customtools": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3-pro-image": {
        "values": [
          "low",
          "high"
        ]
      },
      "gemini-3.1-pro-preview": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.6-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-live-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.5-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3.5-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-flash-lite-latest": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3-flash-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.8-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-flash-latest": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image-preview": {
        "values": [
          "minimal",
          "high"
        ]
      }
    },
    "anthropic": {
      "claude-sonnet-4-6": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "claude-opus-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4-5": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-fable-5-1": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4-6": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "claude-opus-4-7": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-fable-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4-8": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-sonnet-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4-5-20251101": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      }
    },
    "grok": {
      "grok-4.3": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.20-multi-agent-0309": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "grok-4.5": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.6": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      }
    },
    "deepseek": {
      "deepseek-v4-flash-vision-exp": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-pro": {
        "values": [
          "high",
          "max"
        ]
      },
      "deepseek-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      }
    },
    "siliconflow": {
      "glm-5.2": {
        "values": [
          "high",
          "max"
        ]
      }
    },
    "kimi": {
      "kimi-k3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "k3-256k": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "kimi-for-coding": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "k3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      }
    },
    "zhipu": {
      "glm-5.2": {
        "values": [
          "high",
          "max"
        ]
      },
      "glm-5.3-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.3-highspeed": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.2-highspeed": {
        "values": [
          "high",
          "max"
        ]
      }
    },
    "dashscope": {
      "deepseek-v4-flash": {
        "values": [
          "high",
          "max"
        ]
      },
      "qwen3.8-flash": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "qwen3.8-max": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "deepseek-v4-pro": {
        "values": [
          "high",
          "max"
        ]
      },
      "glm-5.3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-flash-0731": {
        "values": [
          "high",
          "max"
        ]
      },
      "glm-5.2": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      }
    },
    "openrouter": {
      "qwen3.8-27b": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "qwen3.8-max-0902": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "qwen3.8-2.4t-a95b": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "claude-fable-latest": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-latest": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-sonnet-latest": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "deepseek-v4-flash-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-pro-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-flash-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "grok-latest": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "step-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "mistral-medium-3-5": {
        "values": [
          "none",
          "high"
        ]
      },
      "mistral-small-2603": {
        "values": [
          "none",
          "high"
        ]
      },
      "nemotron-3-super-120b-a12b": {
        "values": [
          "low",
          "medium"
        ]
      },
      "nemotron-3-ultra-550b-a55b:free": {
        "values": [
          "medium",
          "high"
        ]
      },
      "nemotron-3-super-120b-a12b:free": {
        "values": [
          "low",
          "medium"
        ]
      },
      "nemotron-3-ultra-550b-a55b": {
        "values": [
          "medium",
          "high"
        ]
      },
      "claude-opus-4.8": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4.7": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-sonnet-4.6": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "claude-opus-4.6": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "claude-fable-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-sonnet-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-fable-5.1": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-3.1-pro-preview-customtools": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3.1-pro-preview": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.6-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.5-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3.5-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3-flash-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.8-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image-preview": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "nex-n2.5-mini:free": {
        "values": [
          "none",
          "medium",
          "high"
        ]
      },
      "nex-n2.5-pro:free": {
        "values": [
          "none",
          "medium",
          "high"
        ]
      },
      "inkling-small": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "inkling-small:free": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "inkling:free": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "inkling": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "muse-spark-1.3": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "muse-spark-1.2": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-spark-1.2-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-spark-1.3-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "muse-spark-1.1": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-glimmer-30b": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "seed-2.0-code": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "seed-2.0-mini": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "seed-2.0-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "mercury-2.5": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "mercury-2": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-pro-latest": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-flash-latest": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "fugu-ultra": {
        "values": [
          "high",
          "xhigh",
          "max"
        ]
      },
      "fugu-max": {
        "values": [
          "high",
          "xhigh",
          "max"
        ]
      },
      "sakana-namazu": {
        "values": [
          "none",
          "high"
        ]
      },
      "fugu-ultra-v2": {
        "values": [
          "high",
          "xhigh",
          "max"
        ]
      },
      "kimi-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "granite-4.2-8b": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "deepseek-v4-flash-vision-exp": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-pro-0813": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-flash-0731": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-flash": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "deepseek-v4.1-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4-pro": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "gpt-terra-latest": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-sol-latest": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-luna-latest": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-astra-latest": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-mini-latest": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "grok-4.20-multi-agent": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "grok-4.3": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.5": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.6": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o4-mini-high": {
        "values": [
          "high"
        ]
      },
      "gpt-5-nano": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-pro": {
        "values": [
          "high"
        ]
      },
      "o3-mini-high": {
        "values": [
          "high"
        ]
      },
      "gpt-5.1-codex-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-6-astra-pro": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.1-codex": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.6-sol": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2-codex": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-6-astra": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.6-luna-pro": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-oss-20b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.6-sol-pro": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-oss-safeguard-20b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.1": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.1-codex-max": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-image-2": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-luna": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.3-codex": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-nano": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-terra-pro": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.5-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-mini": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5-mini": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-oss-120b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.4-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-terra": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.5": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "glm-flash-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-latest": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "kimi-k3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "hy3": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "hy4-preview": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "hy3-preview": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "glm-5.2": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "glm-5.3-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.2:free": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "glm-5.3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      }
    },
    "opencodego": {
      "deepseek-v4-flash-vision-exp": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "muse-spark-1.2-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "glm-5.2": {
        "values": [
          "high",
          "max"
        ]
      },
      "deepseek-v4-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "grok-4.5": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "ox-alpha-free": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "deepseek-v4.1-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "hy3": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "hy4-preview": {
        "values": [
          "none",
          "high"
        ]
      },
      "omen-alpha": {
        "values": [
          "low",
          "high"
        ]
      },
      "gpt-5.6-luna": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "kimi-k3": {
        "values": [
          "max"
        ]
      },
      "glm-5.3-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "muse-spark-1.3-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "qwen3.8-flash": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "grok-4.6": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "qwen3.8-max": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "deepseek-v4-pro": {
        "values": [
          "high",
          "max"
        ]
      },
      "glm-5.3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      }
    },
    "mistral": {
      "mistral-medium-latest": {
        "values": [
          "none",
          "high"
        ]
      },
      "mistral-medium-2604": {
        "values": [
          "none",
          "high"
        ]
      },
      "mistral-small-latest": {
        "values": [
          "none",
          "high"
        ]
      },
      "zai-glm-5-2": {
        "values": [
          "high",
          "max"
        ]
      },
      "mistral-small-2603": {
        "values": [
          "none",
          "high"
        ]
      }
    },
    "stepfun": {
      "step-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "step-3.5-flash": {
        "values": [
          "low",
          "high"
        ]
      },
      "step-3.5-flash-2603": {
        "values": [
          "low",
          "high"
        ]
      }
    },
    "vertexai": {
      "gemini-3.1-pro-preview-customtools": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-4-5@20251101": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-pro-preview": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-sonnet-4-6@default": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "gemini-3.6-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "claude-fable-5@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-3.1-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-4-6@default": {
        "values": [
          "low",
          "medium",
          "high",
          "max"
        ]
      },
      "claude-sonnet-5@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-3.5-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3.5-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "claude-fable-5-1@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4-7@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-flash-lite-latest": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-5@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-3-flash-preview": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.8-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-flash-latest": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-4-8@default": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-oss-120b-maas": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-oss-20b-maas": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      }
    },
    "vercel": {
      "step-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "step-3.5-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "interfaze-beta": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "qwen3.8-27b": {
        "values": [
          "none",
          "low",
          "medium",
          "xhigh"
        ]
      },
      "qwen3.8-max-0902": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "qwen3.8-2.4t-a95b": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "qwen3.8-max": {
        "values": [
          "low",
          "medium",
          "xhigh"
        ]
      },
      "grok-4.3": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.5": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "grok-4.6": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-4.8": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "claude-opus-5-fast": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-opus-4.7": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "claude-opus-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "claude-sonnet-4.6": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-opus-4.8-fast": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "claude-opus-4.6": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "claude-fable-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "claude-sonnet-5": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "claude-fable-5.1": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gemini-3.1-pro-preview": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.6-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.5-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3.5-flash-lite": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.7-flash": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gemini-3.1-flash-image-preview": {
        "values": [
          "minimal",
          "high"
        ]
      },
      "gemini-3-flash": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "inkling-small": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "inkling": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "muse-spark-1.3": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "muse-spark-1.2-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-spark-1.3-contributor": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-spark-1.1": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "muse-glimmer-30b": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "seed-1.8": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "seed-2.1-turbo": {
        "values": [
          "none",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "mercury-2.5": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "mercury-2": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "fugu-max": {
        "values": [
          "high",
          "xhigh",
          "max"
        ]
      },
      "fugu-ultra-v2": {
        "values": [
          "high",
          "xhigh",
          "max"
        ]
      },
      "deepseek-v4-flash-vision-exp": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "deepseek-v4-pro-0813": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "deepseek-v4-flash": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "deepseek-v4.1-flash": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "deepseek-v4-pro": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "nova-2-lite": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-fast": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-codex": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-pro": {
        "values": [
          "high"
        ]
      },
      "gpt-5.1-codex-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.5-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.1-codex": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.4-mini-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-sol": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5-mini-fast": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.2-codex": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-6-astra": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-6-astra-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-oss-20b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "o4-mini-fast": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-oss-safeguard-20b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.1-codex-max": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-oss-safeguard-120b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.6-luna": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.6-luna-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.3-codex": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.4-nano": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.1-thinking": {
        "values": [
          "none",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.5-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o3-fast": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.6-terra-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.4-mini": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.3-codex-fast": {
        "values": [
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-oss-120b": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.4-pro": {
        "values": [
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-terra": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-5.2-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.2": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "gpt-5.6-sol-fast": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ]
      },
      "gpt-realtime-2.1": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o3-pro": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5.5": {
        "values": [
          "none",
          "low",
          "medium",
          "high",
          "xhigh"
        ]
      },
      "o3": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "o3-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "o4-mini": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-mini": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "o1": {
        "values": [
          "low",
          "medium",
          "high"
        ]
      },
      "gpt-5-nano": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      },
      "kimi-k3-fast": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "hy3": {
        "values": [
          "none",
          "low",
          "high"
        ]
      },
      "hy4-preview": {
        "values": [
          "none",
          "high"
        ]
      },
      "glm-5.2": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "glm-5.3-fast": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.2-fast": {
        "values": [
          "high",
          "xhigh"
        ]
      },
      "glm-5.3-flash": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "glm-5.3": {
        "values": [
          "low",
          "high",
          "max"
        ]
      },
      "mistral-medium-3.5": {
        "values": [
          "none",
          "high"
        ]
      },
      "sonar-reasoning-pro": {
        "values": [
          "minimal",
          "low",
          "medium",
          "high"
        ]
      }
    }
  },
  "byModelId": {
    "gpt-5-nano": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5-pro": {
      "values": [
        "high"
      ]
    },
    "gpt-5.6-sol": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-6-astra": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.2-pro": {
      "values": [
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.3-codex-spark": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.4": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.1": {
      "values": [
        "none",
        "low",
        "medium",
        "high"
      ]
    },
    "o1": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.6-luna": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.3-codex": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "o1-pro": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.4-nano": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.5-pro": {
      "values": [
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.4-mini": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.6": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5-mini": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.4-pro": {
      "values": [
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.6-terra": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.2": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.2-chat-latest": {
      "values": [
        "medium"
      ]
    },
    "o4-mini": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-realtime-2.1": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "o3-mini": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "o3": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "o3-pro": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.5": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gemini-3.1-pro-preview-customtools": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-lite-image": {
      "values": [
        "minimal",
        "high"
      ]
    },
    "gemini-3-pro-image": {
      "values": [
        "low",
        "high"
      ]
    },
    "gemini-3.1-pro-preview": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.6-flash": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-lite": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-live-preview": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.5-flash": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-lite-preview": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-image": {
      "values": [
        "minimal",
        "high"
      ]
    },
    "gemini-3.5-flash-lite": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-flash-lite-latest": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3-flash-preview": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.8-flash": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.7-flash": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-flash-latest": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-3.1-flash-image-preview": {
      "values": [
        "minimal",
        "high"
      ]
    },
    "claude-sonnet-4-6": {
      "values": [
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "claude-opus-5": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4-5": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "claude-fable-5-1": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4-6": {
      "values": [
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "claude-opus-4-7": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-fable-5": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "claude-opus-4-8": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-sonnet-5": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "claude-opus-4-5-20251101": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "grok-4.3": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "grok-4.20-multi-agent-0309": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "grok-4.5": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "grok-4.6": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "deepseek-v4-flash-vision-exp": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "deepseek-v4-flash": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "deepseek-v4-pro": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "deepseek-flash": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.2": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "kimi-k3": {
      "values": [
        "max"
      ]
    },
    "k3-256k": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "kimi-for-coding": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "k3": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.3-flash": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.3": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.3-highspeed": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.2-highspeed": {
      "values": [
        "high",
        "max"
      ]
    },
    "qwen3.8-flash": {
      "values": [
        "low",
        "medium",
        "xhigh"
      ]
    },
    "qwen3.8-max": {
      "values": [
        "low",
        "medium",
        "xhigh"
      ]
    },
    "deepseek-v4-flash-0731": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "qwen3.8-27b": {
      "values": [
        "none",
        "low",
        "medium",
        "xhigh"
      ]
    },
    "qwen3.8-max-0902": {
      "values": [
        "low",
        "medium",
        "xhigh"
      ]
    },
    "qwen3.8-2.4t-a95b": {
      "values": [
        "low",
        "medium",
        "xhigh"
      ]
    },
    "claude-fable-latest": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-latest": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-sonnet-latest": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "deepseek-v4-flash-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "deepseek-pro-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "deepseek-flash-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "grok-latest": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "step-3.7-flash": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "mistral-medium-3-5": {
      "values": [
        "none",
        "high"
      ]
    },
    "mistral-small-2603": {
      "values": [
        "none",
        "high"
      ]
    },
    "nemotron-3-super-120b-a12b": {
      "values": [
        "low",
        "medium"
      ]
    },
    "nemotron-3-ultra-550b-a55b:free": {
      "values": [
        "medium",
        "high"
      ]
    },
    "nemotron-3-super-120b-a12b:free": {
      "values": [
        "low",
        "medium"
      ]
    },
    "nemotron-3-ultra-550b-a55b": {
      "values": [
        "medium",
        "high"
      ]
    },
    "claude-opus-4.8": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "claude-opus-4.7": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "claude-sonnet-4.6": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "claude-opus-4.6": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "claude-fable-5.1": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "nex-n2.5-mini:free": {
      "values": [
        "none",
        "medium",
        "high"
      ]
    },
    "nex-n2.5-pro:free": {
      "values": [
        "none",
        "medium",
        "high"
      ]
    },
    "inkling-small": {
      "values": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "inkling-small:free": {
      "values": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "inkling:free": {
      "values": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "inkling": {
      "values": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "muse-spark-1.3": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "muse-spark-1.2": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "muse-spark-1.2-contributor": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "muse-spark-1.3-contributor": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "muse-spark-1.1": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "muse-glimmer-30b": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "seed-2.0-code": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "seed-2.0-mini": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "seed-2.0-lite": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "mercury-2.5": {
      "values": [
        "none",
        "low",
        "medium",
        "high"
      ]
    },
    "mercury-2": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gemini-pro-latest": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "fugu-ultra": {
      "values": [
        "high",
        "xhigh",
        "max"
      ]
    },
    "fugu-max": {
      "values": [
        "high",
        "xhigh",
        "max"
      ]
    },
    "sakana-namazu": {
      "values": [
        "none",
        "high"
      ]
    },
    "fugu-ultra-v2": {
      "values": [
        "high",
        "xhigh",
        "max"
      ]
    },
    "kimi-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "granite-4.2-8b": {
      "values": [
        "none",
        "low",
        "high"
      ]
    },
    "deepseek-v4-pro-0813": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "deepseek-v4.1-flash": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "gpt-terra-latest": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-sol-latest": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-luna-latest": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-astra-latest": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-mini-latest": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "grok-4.20-multi-agent": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "o4-mini-high": {
      "values": [
        "high"
      ]
    },
    "o3-mini-high": {
      "values": [
        "high"
      ]
    },
    "gpt-5.1-codex-mini": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-6-astra-pro": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.1-codex": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.2-codex": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.6-luna-pro": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-oss-20b": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.6-sol-pro": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-oss-safeguard-20b": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.1-codex-max": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.4-image-2": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.6-terra-pro": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-oss-120b": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "glm-flash-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-latest": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "hy3": {
      "values": [
        "none",
        "low",
        "high"
      ]
    },
    "hy4-preview": {
      "values": [
        "none",
        "high"
      ]
    },
    "hy3-preview": {
      "values": [
        "none",
        "low",
        "high"
      ]
    },
    "glm-5.2:free": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "ox-alpha-free": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "omen-alpha": {
      "values": [
        "low",
        "high"
      ]
    },
    "mistral-medium-latest": {
      "values": [
        "none",
        "high"
      ]
    },
    "mistral-medium-2604": {
      "values": [
        "none",
        "high"
      ]
    },
    "mistral-small-latest": {
      "values": [
        "none",
        "high"
      ]
    },
    "zai-glm-5-2": {
      "values": [
        "high",
        "max"
      ]
    },
    "step-3.5-flash": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "step-3.5-flash-2603": {
      "values": [
        "low",
        "high"
      ]
    },
    "claude-opus-4-5@20251101": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "claude-sonnet-4-6@default": {
      "values": [
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "claude-fable-5@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4-6@default": {
      "values": [
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "claude-sonnet-5@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-fable-5-1@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4-7@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-5@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4-8@default": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-oss-120b-maas": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-oss-20b-maas": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "interfaze-beta": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "claude-opus-5-fast": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "claude-opus-4.8-fast": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gemini-3-flash": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "seed-1.8": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "seed-2.1-turbo": {
      "values": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "nova-2-lite": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5-fast": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5-codex": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.5-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.4-mini-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5-mini-fast": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-6-astra-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "o4-mini-fast": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-oss-safeguard-120b": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.6-luna-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.4-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.1-thinking": {
      "values": [
        "none",
        "low",
        "medium",
        "high"
      ]
    },
    "o3-fast": {
      "values": [
        "low",
        "medium",
        "high"
      ]
    },
    "gpt-5.6-terra-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "gpt-5.3-codex-fast": {
      "values": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.2-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "gpt-5.6-sol-fast": {
      "values": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "kimi-k3-fast": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.3-fast": {
      "values": [
        "low",
        "high",
        "max"
      ]
    },
    "glm-5.2-fast": {
      "values": [
        "high",
        "xhigh"
      ]
    },
    "mistral-medium-3.5": {
      "values": [
        "none",
        "high"
      ]
    },
    "sonar-reasoning-pro": {
      "values": [
        "minimal",
        "low",
        "medium",
        "high"
      ]
    }
  }
} as const
