import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { createClient, Client } from '@libsql/client'
import { drizzle } from 'drizzle-orm/libsql'
import { SnapshotRepository } from '../snapshot.repository'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'

describe('SnapshotRepository', () => {
  let sqliteDb: Client
  let repo: SnapshotRepository
  let tempDir: string
  let dbPath: string

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'baishou-snapshot-test-'))
    dbPath = path.join(tempDir, 'agent.db')

    sqliteDb = createClient({ url: `file:${dbPath}` })
    const drizzleDb = drizzle(sqliteDb)

    // Install compression_snapshots simply
    await sqliteDb.execute(`
      CREATE TABLE IF NOT EXISTS compression_snapshots (
        id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        session_id TEXT NOT NULL,
        summary_text TEXT NOT NULL,
        covered_up_to_message_id TEXT NOT NULL,
        tail_start_message_id TEXT,
        message_count INTEGER NOT NULL,
        token_count INTEGER,
        created_at INTEGER NOT NULL
      )
    `)
    repo = new SnapshotRepository(drizzleDb)
  })

  afterEach(async () => {
    sqliteDb.close()
    try {
      await fs.rm(tempDir, { recursive: true, force: true })
    } catch (e) {
      // ignore
    }
  })

  it('getLatestSnapshot returns null if no snapshot exists', async () => {
    const res = await repo.getLatestSnapshot('sess-1')
    expect(res).toBeNull()
  })

  it('appendSnapshot properly stores UUID text bindings and loads them', async () => {
    const sessionId = 'acde070d-8c4c-4f0d-9d8a-162843c10333'
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Test summary generated by AI',
      coveredUpToMessageId: 'msg-v4-uuid-test',
      messageCount: 10,
      tokenCount: 154
    })

    const latest = await repo.getLatestSnapshot(sessionId)

    expect(latest).toBeDefined()
    expect(latest!.sessionId).toBe(sessionId)
    expect(latest!.summaryText).toBe('Test summary generated by AI')
    expect(latest!.coveredUpToMessageId).toBe('msg-v4-uuid-test')
    expect(latest!.tokenCount).toBe(154)
    expect(latest!.id).toBeDefined()
    expect(latest!.createdAt).toBeDefined()
  })

  it('getLatestSnapshot returns the newest snapshot based on chronological order', async () => {
    const sessionId = 'uuid-fake-session'

    // Append 3 snapshots
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Snapshot 1',
      coveredUpToMessageId: 'msg-1',
      messageCount: 1,
      tokenCount: null
    })
    await new Promise((resolve) => setTimeout(resolve, 10)) // ensures distinct timestamps
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Snapshot 2',
      coveredUpToMessageId: 'msg-2',
      messageCount: 2,
      tokenCount: null
    })
    await new Promise((resolve) => setTimeout(resolve, 10))
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Snapshot 3',
      coveredUpToMessageId: 'msg-3',
      messageCount: 3,
      tokenCount: null
    })

    const latest = await repo.getLatestSnapshot(sessionId)
    expect(latest).toBeDefined()
    expect(latest!.summaryText).toBe('Snapshot 3')
  })

  it('deleteSnapshotsNotFullyContainedInMessages removes snapshots referencing deleted messages', async () => {
    const sessionId = 'sess-truncate'
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Valid',
      coveredUpToMessageId: 'msg-keep',
      tailStartMessageId: 'msg-tail-keep',
      messageCount: 2,
      tokenCount: null
    })
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Invalid covered',
      coveredUpToMessageId: 'msg-gone',
      messageCount: 1,
      tokenCount: null
    })
    await repo.appendSnapshot({
      sessionId,
      summaryText: 'Invalid tail',
      coveredUpToMessageId: 'msg-keep',
      tailStartMessageId: 'msg-tail-gone',
      messageCount: 2,
      tokenCount: null
    })

    await repo.deleteSnapshotsNotFullyContainedInMessages(
      sessionId,
      new Set(['msg-keep', 'msg-tail-keep'])
    )

    const remaining = await repo.listSnapshotsBySession(sessionId)
    expect(remaining).toHaveLength(1)
    expect(remaining[0]!.summaryText).toBe('Valid')
  })

  it('replaceSnapshotsForSession deletes then inserts portable rows', async () => {
    await repo.appendSnapshot({
      sessionId: 'sess-r',
      summaryText: 'old',
      coveredUpToMessageId: 'old',
      messageCount: 1,
      tokenCount: 1
    })
    await repo.replaceSnapshotsForSession('sess-r', [
      {
        coveredUpToMessageId: 'm2',
        tailStartMessageId: 'm3',
        summaryText: 'new',
        messageCount: 2,
        tokenCount: 8,
        createdAt: 1_700_000_000_000
      }
    ])
    const rows = await repo.listSnapshotsBySession('sess-r')
    expect(rows).toHaveLength(1)
    expect(rows[0]).toMatchObject({
      coveredUpToMessageId: 'm2',
      tailStartMessageId: 'm3',
      summaryText: 'new',
      messageCount: 2,
      tokenCount: 8
    })
  })

  it('deleteBySessionId removes all snapshots of that session', async () => {
    await repo.appendSnapshot({
      sessionId: 'sess-d',
      summaryText: 'gone',
      coveredUpToMessageId: 'm1',
      messageCount: 1,
      tokenCount: null
    })
    await repo.deleteBySessionId('sess-d')
    expect(await repo.getLatestSnapshot('sess-d')).toBeNull()
  })
})
