import { describe, it, expect, vi } from 'vitest'

// Mock database deps
vi.mock('better-sqlite3', () => ({ default: class {} }))
vi.mock('drizzle-orm/better-sqlite3', () => ({ drizzle: () => ({}) }))

describe('SummarySyncService', () => {
  it('should process missing list generated by detector and save via file service', async () => {
    const { SummarySyncService } = await import('../summary-sync.service')

    const fakeMissing = [
      {
        type: 'monthly',
        startDate: new Date(),
        endDate: new Date(),
        label: 'Test Label'
      }
    ]

    const mockDetector = {
      getAllMissing: vi.fn().mockResolvedValue(fakeMissing)
    }

    const mockGenerator = {
      generate: vi.fn().mockImplementation(async function* () {
        yield 'STATUS:thinking_via_test-model'
        yield 'Here is your monthly summary!'
      })
    }

    const mockSummaryRepo = {
      getByDateRange: vi.fn().mockResolvedValue(null),
      findAllByTypeAndStartDay: vi.fn().mockResolvedValue([]),
      upsert: vi.fn().mockResolvedValue({}),
      update: vi.fn()
    }

    const mockFileService = {
      writeSummary: vi.fn().mockResolvedValue(undefined),
      readSummary: vi.fn().mockResolvedValue('Here is your monthly summary!')
    }

    const service = new SummarySyncService(
      mockDetector as any,
      mockGenerator as any,
      mockSummaryRepo as any,
      mockFileService as any
    )

    const callbacks = {
      onProgress: vi.fn(),
      onCompleted: vi.fn(),
      onError: vi.fn()
    }

    await service.syncMissingSummaries(callbacks)

    expect(mockDetector.getAllMissing).toHaveBeenCalled()
    expect(callbacks.onProgress).toHaveBeenCalledWith(fakeMissing[0], 'thinking_via_test-model')
    // 验证写文件调用
    expect(mockFileService.writeSummary).toHaveBeenCalled()
    const writeArgs = mockFileService.writeSummary.mock.calls[0]!
    expect(writeArgs[2]).toBe('Here is your monthly summary!')

    expect(callbacks.onCompleted).toHaveBeenCalled()
    expect(callbacks.onError).not.toHaveBeenCalled()
  })
})
