/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-provider-icons.mjs — do not edit by hand.
 * Source: scripts/provider-icon-lobe.manifest.json + LobeHub static-svg CDN
 */
import openai_mono from '../assets/ai_provider_icon/openai.svg'
import openai_color from '../assets/ai_provider_icon/openai-color.svg'
import gemini_mono from '../assets/ai_provider_icon/gemini.svg'
import gemini_color from '../assets/ai_provider_icon/gemini-color.svg'
import anthropic_mono from '../assets/ai_provider_icon/anthropic.svg'
import grok_mono from '../assets/ai_provider_icon/grok.svg'
import grok_color from '../assets/ai_provider_icon/grok-color.svg'
import deepseek_mono from '../assets/ai_provider_icon/deepseek.svg'
import deepseek_color from '../assets/ai_provider_icon/deepseek-color.svg'
import siliconflow_mono from '../assets/ai_provider_icon/siliconflow.svg'
import siliconflow_color from '../assets/ai_provider_icon/siliconflow-color.svg'
import kimi_mono from '../assets/ai_provider_icon/kimi.svg'
import kimi_color from '../assets/ai_provider_icon/kimi-color.svg'
import xiaomimimo_mono from '../assets/ai_provider_icon/xiaomimimo.svg'
import xiaomimimo_color from '../assets/ai_provider_icon/xiaomimimo-color.svg'
import minimax_mono from '../assets/ai_provider_icon/minimax.svg'
import minimax_color from '../assets/ai_provider_icon/minimax-color.svg'
import zhipu_mono from '../assets/ai_provider_icon/zhipu.svg'
import zhipu_color from '../assets/ai_provider_icon/zhipu-color.svg'
import dashscope_mono from '../assets/ai_provider_icon/dashscope.svg'
import dashscope_color from '../assets/ai_provider_icon/dashscope-color.svg'
import doubao_mono from '../assets/ai_provider_icon/doubao.svg'
import doubao_color from '../assets/ai_provider_icon/doubao-color.svg'
import volcengine_mono from '../assets/ai_provider_icon/volcengine.svg'
import volcengine_color from '../assets/ai_provider_icon/volcengine-color.svg'
import lmstudio_mono from '../assets/ai_provider_icon/lmstudio.svg'
import lmstudio_color from '../assets/ai_provider_icon/lmstudio-color.svg'
import ollama_mono from '../assets/ai_provider_icon/ollama.svg'
import ollama_color from '../assets/ai_provider_icon/ollama-color.svg'
import openrouter_mono from '../assets/ai_provider_icon/openrouter.svg'
import opencodego_mono from '../assets/ai_provider_icon/opencodego.svg'
import mistral_mono from '../assets/ai_provider_icon/mistral.svg'
import mistral_color from '../assets/ai_provider_icon/mistral-color.svg'
import stepfun_mono from '../assets/ai_provider_icon/stepfun.svg'
import stepfun_color from '../assets/ai_provider_icon/stepfun-color.svg'
import hunyuan_mono from '../assets/ai_provider_icon/hunyuan.svg'
import hunyuan_color from '../assets/ai_provider_icon/hunyuan-color.svg'
import vertexai_mono from '../assets/ai_provider_icon/vertexai.svg'
import vertexai_color from '../assets/ai_provider_icon/vertexai-color.svg'
import vercel_mono from '../assets/ai_provider_icon/vercel.svg'
import vercel_color from '../assets/ai_provider_icon/vercel-color.svg'

export const PROVIDER_ICON_REGISTRY = {
  openai: { light: openai_color, dark: openai_mono },
  gemini: { light: gemini_color, dark: gemini_mono },
  anthropic: { light: anthropic_mono, dark: anthropic_mono },
  grok: { light: grok_color, dark: grok_mono },
  deepseek: { light: deepseek_color, dark: deepseek_mono },
  siliconflow: { light: siliconflow_color, dark: siliconflow_mono },
  kimi: { light: kimi_color, dark: kimi_mono },
  xiaomimimo: { light: xiaomimimo_color, dark: xiaomimimo_mono },
  minimax: { light: minimax_color, dark: minimax_mono },
  zhipu: { light: zhipu_color, dark: zhipu_mono },
  dashscope: { light: dashscope_color, dark: dashscope_mono },
  doubao: { light: doubao_color, dark: doubao_mono },
  volcengine: { light: volcengine_color, dark: volcengine_mono },
  lmstudio: { light: lmstudio_color, dark: lmstudio_mono },
  ollama: { light: ollama_color, dark: ollama_mono },
  openrouter: { light: openrouter_mono, dark: openrouter_mono },
  opencodego: { light: opencodego_mono, dark: opencodego_mono },
  mistral: { light: mistral_color, dark: mistral_mono },
  stepfun: { light: stepfun_color, dark: stepfun_mono },
  hunyuan: { light: hunyuan_color, dark: hunyuan_mono },
  vertexai: { light: vertexai_color, dark: vertexai_mono },
  vercel: { light: vercel_color, dark: vercel_mono }
} as const

export type ProviderIconRegistryId = keyof typeof PROVIDER_ICON_REGISTRY

export const PROVIDER_ICON_IDS = Object.keys(PROVIDER_ICON_REGISTRY) as ProviderIconRegistryId[]
